config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  get 'stripe-key', to: "payment#stripe_key"
  post 'pay', to: "payment#pay"

  resources :images
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :images,
            attached: true,
            content_type: ['image/png','image/gif','image/jpeg'],
            size: { less_than: 5.megabytes, message: "must not exceed 5 MB" }

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable

  has_one :payment
  accepts_nested_attributes_for :payment

  has_many_attached :images

  def full_name
    return email
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :find_image_by_id, only: [:show, :edit, :update, :destroy]

  def new
  end

  def show
  end

  def index
    @images = current_user.images.reverse
  end

  def create
    current_user.images.attach(params[:image])
    if current_user.errors.any?
      render :new
    else
      redirect_to images_path
    end

  end

  def update
  end

  def destroy
    if @image.destroy
      flash[:alert] = "#{@image.blob.filename} successfully deleted"
    end
    redirect_to images_path
  end

  private
  def find_image_by_id
    @image = current_user.images.attachments.find(params[:id])
  end
end

app/controllers/payment_controller.rb
require 'stripe'

class PaymentController < ApplicationController
  skip_before_action :authenticate_user!, only: [:stripe_key, :pay]
  skip_before_action :verify_authenticity_token

  def stripe_key
    render json: { publishableKey: Rails.configuration.stripe[:publishable_key] }
  end

  def pay
    data = JSON.parse(request.body.read)
    begin
      if data['paymentMethodId']
        # Create a PaymentIntent with a PaymentMethod ID from the client.
        intent = Stripe::PaymentIntent.create(
            amount: 1000,
            currency: 'eur',
            payment_method: data['paymentMethodId'],
            confirmation_method: 'manual',
            confirm: true,
            use_stripe_sdk: data['useStripeSdk']
        )
      elsif data['paymentIntentId']
        intent = Stripe::PaymentIntent.confirm data['paymentIntentId']
      end
      render json: generate_response(intent)
    rescue Stripe::CardError => e
      render json: { error: e.message }
    end
  end

  def generate_response(intent)
    case intent['status']
    when 'requires_action', 'requires_source_action'
      # Card requires authentication
      return {
          requiresAction: true,
          paymentIntentId: intent['id'],
          clientSecret: intent['client_secret']
      }
    when 'requires_payment_method', 'requires_source'
      # Card was not properly authenticated, new payment method required
      return {
          error: 'Your card was denied, please provide a new payment method'
      }
    when 'succeeded'
      # Payment is complete, authentication not required
      # To cancel the payment you will need to issue a Refund (https://stripe.com/docs/api/refunds)
      puts '💰 Payment received!'
      return {
          clientSecret: intent['client_secret']
      }
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def create
    build_resource(sign_up_params)

    resource.class.transaction do
      resource.save
      yield resource if block_given?
      if resource.persisted?
        @payment = Payment.new({user_id: resource.id, payment_method_id: params[:payment][:payment_method_id], product_id: params[:payment][:product_id]})
        @payment.save
        if resource.active_for_authentication?
          set_flash_message! :notice, :signed_up
          sign_up(resource_name, resource)
          respond_with resource, location: after_sign_up_path_for(resource)
        else
          set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
          expire_data_after_sign_in!
          respond_with resource, location: after_inactive_sign_up_path_for(resource)
        end
      else
        # rollback payment!
        clean_up_passwords resource
        set_minimum_password_length
        respond_with resource
      end
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/edit.html.erb
<h1>Images#edit</h1>
<p>Find me in app/views/images/edit.html.erb</p>

app/views/images/index.html.erb
<h1>Image portfolio</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Preview</th>
      <th scope="col">Filename</th>
      <th scope="col">Size</th>
      <th scope="col">Date</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
  <% @images.each do |image| %>
    <tr>
      <th scope="row">1<%= image.id %></th>
      <td>
        <%= link_to image_path(image) do %>
          <%= image_tag image.variant(resize_to_limit: [150, 150]) %>
        <% end %>
      </td>
      <td>
        <%= link_to image_path(image) do %>
          <%= truncate(image.blob.filename.to_s, length: 20) %>
        <% end %>
      </td>
      <td><%= number_to_human_size(image.blob.byte_size) %></td>
      <td><%= image.blob.created_at.strftime("%d.%m.%Y") %></td>
      <td>
        <%= link_to "Edit", edit_image_path(image), class: "btn btn-sm btn-success" %>
        <%= link_to "Delete", image_path(image), method: :delete, class: "btn btn-sm btn-danger", data: { confirm: "Are you sure?" } %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/images/new.html.erb
<h1>Upload new images to your portfolio</h1>

<%= render 'shared/errors', obj: current_user %>

<%= form_with model: @image, url: images_path, local: true do |f| %>
  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, accept: 'image/png,image/gif,image/jpeg', class: "form-control-file" %>
    <div class="invalid-feedback" id="image-errors">
    </div>
  </div>
  <div class="form-group">
      <%= f.submit "Upload", class: "btn btn-primary" %>
  </div>
<% end %>

<% content_for :page_scripts do %>
  <script>
    document.addEventListener('DOMContentLoaded', function() {
        var img = document.getElementById('image');
        img.addEventListener('change', function(e) {
            if (e.target.files[0].size / 1024 / 1024 > 3) {
                alert("Max image size is 3 MB!");
            }
        });
    });
  </script>
<% end %>

app/views/images/show.html.erb
<h1>Images#show</h1>
<p>Find me in app/views/images/show.html.erb</p>

<div class="row">
  <div class="col-md-12 text-center">
    <%= image_tag @image, class: "img-fluid" %>
  </div>
</div>

app/views/layouts/_flash_messages.html.erb
<% if notice || alert %>
  <div class="col-12 alert alert-<%= notice ? "success" : "danger" %> alert-dismissible fade show" role="alert">
    <%= notice ? notice : alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% else %>
  <div class="row flash-messages">
    <div class="col-sm-12">
      <% flash.each do |name, msg| %>
        <div class='alert alert-<%= "#{name}" %>'>
          <%= msg %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to "Photo-App", root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item <%= 'active' if request.path == root_path %>">
        <%= link_to 'Home', root_path, class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Images
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "New Image", new_image_path, class: "dropdown-item" %>
          <%= link_to '#', class: "dropdown-item" do %>
            <%= fa_icon "edit", class: "mr-1" %> Edit Photos
          <% end %>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
    </ul>
    <% if current_user %>
      <ul class="navbar-nav mr-3">
        <li class="nav-item navbar-text">
          <%= fa_icon "user", class: "mr-1" %> <%= link_to current_user.full_name, edit_user_registration_path, class: "btn btn-sm btn-link" %>
        </li>
      </ul>
      <ul class="navbar-nav">
        <li class="nav-item">
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "btn btn-sm btn-danger" %>
        </li>
      </ul>
    <% else %>
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Sign in", new_user_session_path, class: "btn btn-sm btn-primary" %>
        </li>
      </ul>
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Sign up", new_user_registration_path, class: "btn btn-sm btn-link" %>
        </li>
      </ul>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhotoApp</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <div class="container mt-4">
      <div class="row">
        <%= render 'layouts/flash_messages' %>
      </div>
      <%= yield %>

      <%= yield :page_scripts %>
    </div>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="col-sm-12">
      <div class="alert alert-danger">
        <h5 class="alert-heading">Found <%= pluralize obj.errors.count, 'error' %></h5>
        <small>
          <ul>
            <% obj.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </small>
      </div>
    </div>
  </div>
<% end %>

app/views/welcome/index.html.erb
<% if current_user %>
  <h3>Welcome <%= current_user.full_name %></h3>
<% else %>
  <div class="row">
    <div class="jumbotron main-teaser col-12">
      <div class="container">
        <h2 class="display-4">Welcome to Photo Management App</h2>
        <p class="lead">Manage all your photos from within on app. Sign up now!</p>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="card-deck col-12 mb-3 text-center">
      <div class="card mb-4 shadow-sm">
        <div class="card-header">
          <h4 class="my-0 font-weight-normal">Standard</h4>
        </div>
        <div class="card-body">
          <h1 class="card-title pricing-card-title">10 EUR</h1>
          <ul class="list-unstyled mt-3 mb-4">
            <li>2 GB of storage</li>
            <li>Website access</li>
            <li>Email support</li>
          </ul>
          <%= link_to 'Sign up', new_user_registration_path, class: "btn btn-lg btn-block btn-outline-primary" %>
        </div>
      </div>
      <div class="card mb-4 shadow-sm">
        <div class="card-header">
          <h4 class="my-0 font-weight-normal">Pro</h4>
        </div>
        <div class="card-body">
          <h1 class="card-title pricing-card-title">30 EUR</h1>
          <ul class="list-unstyled mt-3 mb-4">
            <li>Unlimited photo upload</li>
            <li>Access anywhere</li>
            <li>Priority email support</li>
          </ul>
          <%= link_to 'Sign up', new_user_registration_path, class: "btn btn-lg btn-block btn-primary" %>
        </div>
      </div>
    </div>
  </div>
<% end %>